// todo-app/reactjs/src/page/Todo.js
import { useState, useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import todosAction from "./../redux/action/todos";

import { MdDone, MdRemove, MdAdd, MdEdit } from "react-icons/md";

import "./../page/Todo.css";

export default function Todo(props) {
	const dispatch = useDispatch();
	const todos = useSelector((state) => state.todos);
	const [editing, setEditing] = useState(null);
	const [form, setForm] = useState({
		title: "",
		completed: false,
	});

	function handleFormChange(e, key) {
		setForm({
			...form,
			title: e.target.value,
		});
	}

	function handleForm() {
		if (form.title.trim().length <= 0) return;
		editing === null ? store(form) : update(form);
		flush();
	}

	function handleSubmit(e) {
		e.preventDefault();
		handleForm();
	}

	function flush() {
		setEditing(null);
		setForm({ title: "", completed: false });
	}

	function setEditingForm(todo) {
		setEditing(todo);
		setForm({ ...todo });
	}

	function renderTodos() {
		return (
			todos.length > 0 &&
			todos.map(
				(todo) =>
					!todo.completed && (
						<tr className="todo__tr">
							<td className="todo__td" onClick={() => setEditingForm(todo)}>
								{todo.title}
							</td>
							<td className="todo__td">
								<button className="todo__button todo__complete" onClick={() => done(todo)}>
									<MdDone color="#fff" size={20} />
								</button>
								<button className="todo__button todo__remove" onClick={() => remove(todo)}>
									<MdRemove color="#fff" size={20} />
								</button>
							</td>
						</tr>
					)
			)
		);
	}

	async function index() {
		const res = await fetch(`http://localhost:3000/todo`)
			.then((res) => res.json())
			.then((res) => res);

		dispatch(todosAction().set(res));
		flush();
	}

	async function store(todo) {
		await fetch(`http://localhost:3000/todo`, {
			method: "post",
			body: JSON.stringify({ ...todo }),
			headers: {
				"Content-Type": "application/json",
				accept: "application/json, text/plain, */*",
			},
		})
			.then((res) => res.json())
			.then((res) => res);

		index();
	}

	async function update(todo) {
		await fetch(`http://localhost:3000/todo/${todo.id}`, {
			method: "put",
			body: JSON.stringify({ ...todo, title: form.title }),
			headers: {
				"Content-Type": "application/json",
				accept: "application/json, text/plain, */*",
			},
		})
			.then((res) => res.json())
			.then((res) => res);

		index();
	}

	async function done(todo) {
		await fetch(`http://localhost:3000/todo/${todo.id}`, {
			method: "put",
			body: JSON.stringify({ ...todo, completed: true }),
			headers: {
				"Content-Type": "application/json",
				accept: "application/json, text/plain, */*",
			},
		})
			.then((res) => res.json())
			.then((res) => res);

		index();
	}

	async function remove(todo) {
		await fetch(`http://localhost:3000/todo/${todo.id}`, {
			method: "delete",
		})
			.then((res) => res.json())
			.then((res) => res);

		index();
	}

	useEffect(() => {
		index();
	}, []);

	return (
		<div className="todo">
			<h1 className="todo__title">Todo App (ReactJS)</h1>
			<a target="_blank" href="https://github.com/felipetiwamoto" className="todo__made_by">
				Made by Felipe T. Iwamoto
			</a>
			<div className="todo__content">
				<form onSubmit={(e) => handleSubmit(e)} className="todo__form">
					<input
						type="text"
						className="todo__field"
						placeholder="Ex: Study..."
						value={form.title}
						onChange={(e) => handleFormChange(e, "title")}
					/>
					<button type="button" className="todo__button" onClick={() => handleForm()}>
						{editing === null ? <MdAdd color="#fff" size={24} /> : <MdEdit color="#fff" size={24} />}
					</button>
				</form>
				<table className="todo__table">
					<thead className="todo__thead">
						<tr className="todo__tr">
							<th className="todo__th">Title</th>
							<th className="todo__th">Action</th>
						</tr>
					</thead>
					<tbody className="todo__tbody">{renderTodos()}</tbody>
				</table>
			</div>
		</div>
	);
}

// todo-app/angular/src/app/page/todo/todo.component.ts
import { Component, OnInit } from '@angular/core';
import { Todo } from './todo.model';
import { TodoService } from './todo.service';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.scss'],
})
export class TodoComponent implements OnInit {
  editing: Todo | undefined | null = null;
  todos: Array<Todo> = [];
  form: Todo = {
    title: '',
    completed: false,
  };

  constructor(private todoService: TodoService) {}

  ngOnInit(): void {
    this.index();
  }

  index(): void {
    this.todoService
      .index()
      .subscribe((res) => (this.todos = res.filter((row) => !row.completed)));
    this.flush();
  }

  store(todo: Todo): void {
    this.todoService.store(todo).subscribe(() => this.index());
  }

  update(todo: Todo): void {
    this.todoService.update(todo).subscribe(() => this.index());
  }

  done(todo: Todo): void {
    this.todoService
      .done({ ...todo, completed: true })
      .subscribe(() => this.index());
  }

  remove(todo: Todo): void {
    this.todoService.remove(todo).subscribe(() => this.index());
  }

  setEditing(todo: Todo) {
    this.editing = todo;
    this.form = { ...todo };
  }

  handleFormChange($event: any, key: string): void {
    this.form = {
      ...this.form,
      [key]: $event.target.value,
    };
  }

  handleForm(): void {
    this.editing === null ? this.store(this.form) : this.update(this.form);
    this.flush();
  }

  handleSubmit($event: any): void {
    $event.preventDefault();
    if (this.form.title.trim().length <= 0) return;
    this.handleForm();
  }

  flush(): void {
    this.editing = null;
    this.form = {
      title: '',
      completed: false,
    };
  }
}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Todo App | Angular | Made by Felipe T. Iwamoto</title>
  </head>
  <body>
    <div class="todo">
      <h1 class="todo__title">Todo App (Angular)</h1>
      <a target="_blank" href="#" class="todo__made_by"
        >Made by Felipe T. Iwamoto</a
      >
      <div class="todo__content">
        <form (submit)="handleSubmit($event)" class="todo__form">
          <input
            type="text"
            class="todo__field"
            placeholder="Ex: Study..."
            [value]="form.title"
            (input)="handleFormChange($event, 'title')"
          />
          <button
            *ngIf="editing === null"
            type="button"
            class="todo__button"
            (click)="handleForm()"
          >
            <mat-icon>add</mat-icon>
          </button>
          <button
            *ngIf="editing !== null"
            type="button"
            class="todo__button"
            (click)="handleForm()"
          >
            <mat-icon>edit</mat-icon>
          </button>
        </form>
        <table class="todo__table">
          <thead class="todo__thead">
            <tr class="todo__tr">
              <th class="todo__th">Title</th>
              <th class="todo__th">Action</th>
            </tr>
          </thead>
          <tbody class="todo__tbody">
            <tr class="todo__tr" *ngFor="let todo of todos">
              <td class="todo__td" (click)="setEditing(todo)">
                {{ todo.title }}
              </td>
              <td class="todo__td">
                <button
                  class="todo__button todo__complete"
                  (click)="done(todo)"
                >
                  <mat-icon>done</mat-icon>
                </button>
                <button
                  class="todo__button todo__remove"
                  (click)="remove(todo)"
                >
                  <mat-icon color="warn">remove</mat-icon>
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>
